### ISSUE TITLE
ThinLinc Configuration

### ISSUE THREAD

**Issue by moetiker** [jens-maus/thinRoot#1]
Hi

Thanks a lot for the cool project. Thinlinc client is running but I can't configure port number and other client settings.

is there a place where I can preset this in a thinlincrc file .... 

found some infos in the script: S42LoadNetFiles . is there any documentation of the concept or some examples files ... In my case tftp server and config web server are not the same host...

**Comment by jens-maus** [comment]
Thanks for asking here on thinRoot specifics. Yes, we are unfortunately lacking quite some documentation and I would be happy to work on a much broader documentation base but I think some help would be required to get this new project going and better distributed. So if you are interested I would be happy to answer all your questions and then you could in fact prepare some more detailed documentation on setup/installation and tuning (e.g. in the wiki section here).

Regarding your question on client-based settings for ThinLinc, etc. All the methods I implemented in thinRoot are largely borrowed from our previous thinstation-based solution (see https://github.com/hzdr/thinstation) which we used as a base for this new project. Thus, all the logic in `/etc/init.d/S42LoadNetFiles` is actually trying to replicate what is usually done in thinstation netfiles on the TFTP server.

So maintaining specific ThinLinc settings per client or client group you can in fact e.g. use the `thinroot.conf.network` file usually located in `/tftpboot/thinroot/conf`(in our case). In our case we are having the following default ThinLinc related settings:

```
SESSION_0_THINLINC_CONFIG_SOUND_ENABLED=1
SESSION_0_THINLINC_CONFIG_REMOVE_CONFIGURATION=0
SESSION_0_THINLINC_CONFIG_SOUND_SYSTEM=AUTO
SESSION_0_THINLINC_CONFIG_NFS_SERVER_ENABLED=1
SESSION_0_THINLINC_CONFIG_NFS_EXPORTS=/run/usbmount,rw
SESSION_0_THINLINC_CONFIG_LOWERCASE_LOGIN_NAME=1
SESSION_0_THINLINC_CONFIG_JPEG_COMPRESSION=0
SESSION_0_THINLINC_CONFIG_HOST_ALIASES=
SESSION_0_THINLINC_CONFIG_OPTIONS_POPUP_KEY=
SESSION_0_THINLINC_CONFIG_ALLOW_HOSTKEY_UPDATE=0
SESSION_0_THINLINC_CONFIG_UPDATE_ENABLED=0
```

All these settings are then upon bootup of thinroot copied into `/home/truser/.thinlinc/tlclient.conf` within the `qutselect-startup.sh` script we are using (see here https://github.com/jens-maus/thinRoot/blob/master/buildroot-external/rootfs-overlay/bin/qutselect-startup.sh#L52-L70). Thus, using this mechanism you should be able to override the default port, etc. in `tlclient.conf` to your likes.

In addition, please see an example  directory tree we are using in our `/tftpboot` directory for thinroot:

```
/tftpboot/thinroot
/tftpboot/thinroot/conf
/tftpboot/thinroot/conf/qutselect.motd
/tftpboot/thinroot/conf/qutselect.slist
/tftpboot/thinroot/conf/thinroot.conf-PC123
/tftpboot/thinroot/conf/thinroot.conf.group-DEPARTMENTA
/tftpboot/thinroot/conf/thinroot.conf.network
/tftpboot/thinroot/conf/thinroot.hosts
/tftpboot/thinroot/overlay
/tftpboot/thinroot/overlay.pkg
/tftpboot/thinroot/overlay_gen.sh
/tftpboot/thinroot/thinroot.img
```

So if you are familiar how tftp-based config files looked in a thinstation setup you should at least get an idea how to set this up with thinRoot as well.

And then in the PXE setup we are using the following settings in a `thinroot.cfg` file under `/tftpboot/pxelinux.cfg` directory:

```
LABEL 	   thinroot
MENU LABEL ^thinRoot (default)
KERNEL     http://X.X.X.X/thinroot/thinroot.img
APPEND     console=tty2 kgdboc=tty2 noswap elevator=deadline consoleblank=120 quiet loglevel=0
TEXT HELP
Our thinRoot Environment
ENDTEXT
```

And as said, don't hesitate to ask questions if you have problems with setting up an example thinRoot installation on your TFTP/PXE server.
