### ISSUE TITLE
bzImage missing

### ISSUE THREAD

**Issue by oetiker** [jens-maus/thinRoot#2]
Wanted to try thinRoot, following the README ... unfortunately it seems that bzImage is not part of the release. I have now started 'make dist' to see where this gets me.

**Comment by oetiker** [comment]
I have spent some quality time with your server and out came https://github.com/oetiker/thinRoot thanks for the great startingpoint

**Comment by jens-maus** [comment]
Thanks for the heads up! But please be so kind and contribute to OSS by submitting at least part of your changes  as pull requests to this upstream project so that your fork won't get too incompatible over time which would make bug/feature transfers between these two repositories way easier!

**Comment by oetiker** [comment]
well I did not really change your code except for the configuration ... for flexibility and performance reasons I have introduced a specialized boot-server and done some overrides. I also added remmina ... 

have a look at the diff between our trees, if you think some part of it would make sense in your tree, I will be glad to adapt and PR.

**Comment by jens-maus** [comment]
I quickly looked over your changes already and I really think at least some changes would make sense to be send upstream. For one, the remmina package would be great to be moved upstream (why are you not using freerdp, btw?!?)

And regarding the boot-server. Why didn't you simply use lighttpd or nginx as a serving http server and invented boot-server providng the cfg files via HTTP in first place? This sounds like reinventing the wheel to me to some extend, isn't it? What are the pros/cons regarding the boot server?

**Comment by oetiker** [comment]
remmina is just a frontend for freerdp ... in my use case we have simply two kinds of users ... the thinlinc ... they go directly to thinlinc and the remmina they go directly to remmina ... 

remmina unfortunately is not yet in all that good a state ... many icons are missing guess it does not like to be started outside of a gnome/mate/... environment ... 

the boot server serves what the client needs without the client trying multiple times and it can nicely package up directory trees on the fly ... which makes maintenance much simpler than having to rebuild overplay pkg files ... 

and above all it provides for a way to have clients upload their configuration ... so when someone modifies their thinlinc config it gets stored on the boot-server ...
